#ifndef _UMEETING_RTCEVENTDEFINE_H_
#define _UMEETING_RTCEVENTDEFINE_H_

const int RTC_EVENT_PRTC = 10000;
const int RTC_EVENT_AGORA = 10001;
const int RTC_EVENT_ZEGO = 10002;

const int PRTC_EVENT_MSG_BASE = 1024 + 1;
const int PRTC_EVENT_MSG_JOINROOM_RSP = PRTC_EVENT_MSG_BASE + 1;
const int PRTC_EVENT_MSG_LEAVEROOM_RSP = PRTC_EVENT_MSG_BASE + 2;
const int PRTC_EVENT_MSG_USERJOIN_NOTIFY = PRTC_EVENT_MSG_BASE + 3;
const int PRTC_EVENT_MSG_REJOINING = PRTC_EVENT_MSG_BASE + 4;
const int PRTC_EVENT_MSG_ERRORMSG = PRTC_EVENT_MSG_BASE + 5;
const int PRTC_EVENT_MSG_REMOTEUSERJOIN = PRTC_EVENT_MSG_BASE + 6;
const int PRTC_EVENT_MSG_REMOTEUSERLEAVE = PRTC_EVENT_MSG_BASE + 7;

const int PRTC_EVENT_MSG_LOCALPUBLISH_RSP = PRTC_EVENT_MSG_BASE + 8;
const int PRTC_EVENT_MSG_LOCALUNPUBLISH_RSP = PRTC_EVENT_MSG_BASE + 9;
const int PRTC_EVENT_MSG_REMOTEPUBLISH = PRTC_EVENT_MSG_BASE + 10;
const int PRTC_EVENT_MSG_REMOTEUNPUBLISH = PRTC_EVENT_MSG_BASE + 11;
const int PRTC_EVENT_MSG_REMOTESUB_RSP = PRTC_EVENT_MSG_BASE + 12;
const int PRTC_EVENT_MSG_REMOTEUNSUBE_RSP = PRTC_EVENT_MSG_BASE + 13;
const int PRTC_EVENT_MSG_KICKOFF = PRTC_EVENT_MSG_BASE + 14;

const int PRTC_EVENT_MSG_LOCALSTREAMMUTE_RSP = PRTC_EVENT_MSG_BASE + 15;
const int PRTC_EVENT_MSG_REMOTESTREAMMUTE_RSP = PRTC_EVENT_MSG_BASE + 16;
const int PRTC_EVENT_MSG_REMOTETRACKST = PRTC_EVENT_MSG_BASE + 17;

const int PRTC_EVENT_MSG_REJOINED = PRTC_EVENT_MSG_BASE + 18;
const int PRTC_EVENT_MSG_REMOTE_AUDIOVOL = PRTC_EVENT_MSG_BASE + 19;
const int PRTC_EVENT_MSG_LOCAL_AUDIOVOL = PRTC_EVENT_MSG_BASE + 20;
const int PRTC_EVENT_MSG_REMOTE_ST_UPDATE = PRTC_EVENT_MSG_BASE + 21;
const int PRTC_EVENT_MSG_LOCAL_ST_UPDATE = PRTC_EVENT_MSG_BASE + 22;

const int PRTC_EVENT_MSG_ELEC_STARTRECORD = PRTC_EVENT_MSG_BASE + 23;
const int PRTC_EVENT_MSG_ELEC_STOPRECORD = PRTC_EVENT_MSG_BASE + 24;

const int PRTC_EVENT_MSG_ONSERVERDIS = PRTC_EVENT_MSG_BASE + 25;
const int PRTC_EVENT_MSG_DEVICE = PRTC_EVENT_MSG_BASE + 26;

const int PRTC_EVENT_MSG_NETWORK_QUA = PRTC_EVENT_MSG_BASE + 27;

const int PRTC_EVENT_MSG_RTMP = PRTC_EVENT_MSG_BASE + 28;
const int PRTC_EVENT_MSG_END = PRTC_EVENT_MSG_BASE + 1000;

#endif
